version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      # Specify a name for the group, which will be used in pull request titles
      # and branch names
      npm-prod-dependencies:
        applies-to: version-updates
        dependency-type: "production"
      npm-dev-dependencies:
        dependency-type: "development"
        applies-to: version-updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      # Specify a name for the group, which will be used in pull request titles
      # and branch names
      actions-dependencies:
        applies-to: version-updates # Applies the group rule to version updates
        patterns:
          - "*"       # A wildcard that matches all dependencies in the package
                      # ecosystem. Note: using "*" may open a large pull request
