version: 2
updates:
- package-ecosystem: "npm"
  directory: "/"
  commit-message:
    prefix: "npm"
  assignees:
    - "Harvester57"
  schedule:
    interval: "cron"
    cronjob: "0 18 * * *"
    timezone: "Europe/Paris"
  groups:
    npm-prod-dependencies:
      applies-to: version-updates
      dependency-type: "production"
    npm-dev-dependencies:
      applies-to: version-updates
      dependency-type: "development"
  ignore:
    - dependency-name: "*"
      update-types: [ "version-update:semver-major" ]
- package-ecosystem: "github-actions"
  directory: "/"
  commit-message:
    prefix: "actions"
  assignees:
  - "Harvester57"
  schedule:
    interval: "cron"
    cronjob: "0 18 * * *"
    timezone: "Europe/Paris"
  groups:
    actions-dependencies:
      applies-to: version-updates # Applies the group rule to version updates
      patterns:
      - "*"
